"""Initial migration

Revision ID: b406c2b057bf
Revises: eb8c6ba3dc8c
Create Date: 2025-09-25 14:22:21.614609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b406c2b057bf'
down_revision = 'eb8c6ba3dc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('target_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Float(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.alter_column('goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('progress')
        batch_op.drop_column('target_date')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
